apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: btcloud-site-cert
spec:
  secretName: btcloud-site-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: btcloud.site
  dnsNames:
  - btcloud.site
  - www.btcloud.site
  - back.btcloud.site